name: Update Pull Request Name

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  update-pr-name:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set Pull Request Name
      id: set-pr-name
      run: |
        LAST_PR_NUMBER=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/pulls?base=develop" | jq -r 'map(select(.state == "open" or .state == "closed")) | max_by(.number) | .number')
        NEXT_PR_NUMBER=$((LAST_PR_NUMBER + 1))
        NEW_PR_NAME="CXT-$NEXT_PR_NUMBER: ${{ github.event.pull_request.title }}"
        echo "::set-output name=new_pr_name::$NEW_PR_NAME"
      
    - name: Update Pull Request Title
      run: |
        NEW_PR_NAME="${{ steps.set-pr-name.outputs.new_pr_name }}"
        echo "Updating pull request title to: $NEW_PR_NAME"
        curl -X PATCH \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -d "{\"title\":\"$NEW_PR_NAME\"}" \
          "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}"
